const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"仓库信息管理",
                        "menuJump":"列表",
                        "tableName":"cangku"
                    }
                ],
                "menu":"仓库信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"仓库类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryCangku"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"公告类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryNews"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"货物类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryXianhua"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改"
                        ],
                        "menu":"出入库类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryXianhuaChuruInout"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"分库管理员管理",
                        "menuJump":"列表",
                        "tableName":"fenkuguanli"
                    }
                ],
                "menu":"分库管理员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告信息管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"公告信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"货物管理",
                        "menuJump":"列表",
                        "tableName":"xianhua"
                    }
                ],
                "menu":"货物管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"出入库管理",
                        "menuJump":"列表",
                        "tableName":"xianhuaChuruInout"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"出入库详情管理",
                        "menuJump":"列表",
                        "tableName":"xianhuaChuruInoutList"
                    }
                ],
                "menu":"出入库管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"员工管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"员工管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改"
	                    ],
	                    "menu":"仓库信息管理",
	                    "menuJump":"列表",
	                    "tableName":"cangku"
	                }
	            ],
	            "menu":"仓库信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"公告信息管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"公告信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改"
	                    ],
	                    "menu":"货物管理",
	                    "menuJump":"列表",
	                    "tableName":"xianhua"
	                }
	            ],
	            "menu":"货物管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"出入库管理",
	                    "menuJump":"列表",
	                    "tableName":"xianhuaChuruInout"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"出入库详情管理",
	                    "menuJump":"列表",
	                    "tableName":"xianhuaChuruInoutList"
	                }
	            ],
	            "menu":"出入库管理"
	        }
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"分库管理员",
	    "tableName":"fenkuguanli"
	},
	    {
	        "backMenu":[
	            {
	                "child":[
	                    {
	                        "buttons":[
	                            "查看"
	                        ],
	                        "menu":"仓库信息管理",
	                        "menuJump":"列表",
	                        "tableName":"cangku"
	                    }
	                ],
	                "menu":"仓库信息管理"
	            }
	            ,{
	                "child":[
	                    {
	                        "buttons":[
	                            "查看"
	                        ],
	                        "menu":"公告信息管理",
	                        "menuJump":"列表",
	                        "tableName":"news"
	                    }
	                ],
	                "menu":"公告信息管理"
	            }
	            ,{
	                "child":[
	                    {
	                        "buttons":[
	                            "查看"
	                        ],
	                        "menu":"货物管理",
	                        "menuJump":"列表",
	                        "tableName":"xianhua"
	                    }
	                ],
	                "menu":"货物管理"
	            }
	            ,{
	                "child":[
	                    {
	                        "buttons":[
	                            "查看",
	                            "新增"
	                        ],
	                        "menu":"出入库管理",
	                        "menuJump":"列表",
	                        "tableName":"xianhuaChuruInout"
	                    }
	                    ,
	                    {
	                        "buttons":[
	                            "查看"
	                        ],
	                        "menu":"出入库详情管理",
	                        "menuJump":"列表",
	                        "tableName":"xianhuaChuruInoutList"
	                    }
	                ],
	                "menu":"出入库管理"
	            }
	        ],
	        "frontMenu":[],
	        "hasBackLogin":"是",
	        "hasBackRegister":"否",
	        "hasFrontLogin":"否",
	        "hasFrontRegister":"否",
	        "roleName":"员工",
	        "tableName":"yonghu"
	    }
]
    }
}
export default menu;
